---
on:
  pull_request:
  push:
    tags:
      - "os_v*" # Trigger on tags starting with "v"

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    uses: chef/github-workflows/.github/workflows/markdown-lint.yml@main

  markdown-link-checker:
    uses: chef/github-workflows/.github/workflows/markdown-link-checker.yml@main

  yaml-lint:
    uses: chef/github-workflows/.github/workflows/yaml-lint.yml@main

  json-lint:
    uses: chef/github-workflows/.github/workflows/json-lint.yml@main

  xml-lint:
    uses: chef/github-workflows/.github/workflows/xml-lint.yml@main

  shellcheck-lint:
    uses: chef/github-workflows/.github/workflows/shellcheck-lint.yml@main

  powershell-lint:
    uses: chef/github-workflows/.github/workflows/powershell-lint.yml@main

  packer-iso-check:
    uses: chef/github-workflows/.github/workflows/packer-iso-url-checker.yml@main
    with:
      EXCLUDE_REGEX: 'amazonlinux-2.*|rhel.*|sles.*|solaris.*|windows-11-aarch64.*,macos-*'

  pkr-bld-virtualbox-arm64:
    uses: ./.github/workflows/pkr-bld-virtualbox-arm64.yml
    secrets: inherit

  pkr-bld-virtualbox-x64:
    uses: ./.github/workflows/pkr-bld-virtualbox-x64.yml
    secrets: inherit

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release was automatically created for tag ${{ github.ref_name }}.
          draft: false
          prerelease: false

  publish-artifacts:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - pkr-bld-virtualbox-arm64
      - pkr-bld-virtualbox-x64
      - create-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./artifacts
          asset_name: pkr-build-artifacts.zip
          asset_content_type: application/zip
          
  check_jobs_pass:
    if: always()
    needs:
      - markdown-lint
      - yaml-lint
      - json-lint
      - xml-lint
      - powershell-lint
      - shellcheck-lint
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          allowed-failures:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}