---
on:
  workflow_call:
  workflow_dispatch:

env:
  PACKER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  # PACKER_LOG: "1"

jobs:
  aarch64:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-11
          - debian-12
          - ubuntu-22.04
          - ubuntu-24.04
        provider:
          - virtualbox-iso
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Vagrant Virtualbox
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudp gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y vagrant virtualbox
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
        with:
          version: 24.2.1058
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Install Bento
        run: |
          eval "$(chef shell-init bash)"
          gem build bento.gemspec
          gem install bento-*.gem
      - name: Bento build
        run: |
          eval "$(chef shell-init bash)"
          bento build -o ${{ matrix.provider }}.vm --vars 'ssh_timeout=30m' os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-aarch64.pkrvars.hcl"
          ls -alh builds/
          cat builds/${{ matrix.os }}*-aarch64._metadata.json
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}-virtualbox-aarch64"
          path: |
            builds/*.box
            builds/*.json
          overwrite: true
          retention-days: 10
          compression-level: 0 # no compression
      - name: Bento Test
        run: |
          eval "$(chef shell-init bash)"
          bento test
